name: Auto-merge exercism-solutions-syncer PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.user.login == 'exercism-solutions-syncer' ||
      github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]'
    
    steps:
      - name: Log PR details
        run: |
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "PR Branch: ${{ github.event.pull_request.head.ref }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
      
      - name: Check if PR is from exercism-sync branch
        id: check-branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" =~ ^exercism-sync/.* ]]; then
            echo "✅ PR is from exercism-sync branch"
            echo "is_sync_branch=true" >> $GITHUB_OUTPUT
          else
            echo "❌ PR is not from exercism-sync branch"
            echo "is_sync_branch=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Auto-approve and enable auto-merge
        if: steps.check-branch.outputs.is_sync_branch == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          
          echo "🔍 Approving PR #${PR_NUMBER}..."
          gh pr review ${PR_NUMBER} --repo ${REPO} --approve --body "✅ Auto-approved: exercism-sync PR"
          
          echo "🔄 Enabling auto-merge for PR #${PR_NUMBER}..."
          gh pr merge ${PR_NUMBER} --repo ${REPO} --auto --merge
          
          echo "✅ Auto-merge enabled successfully!"
      
      - name: Skip non-sync branch
        if: steps.check-branch.outputs.is_sync_branch == 'false'
        run: |
          echo "⏭️ Skipping auto-merge: PR is not from exercism-sync branch"
